In [1]:
import numpy as np

In [2]:
np?  # numpy built-in doc

In [3]:
np.  # press <TAB> to display all the contents of numpy namespace

SyntaxError: invalid syntax (3743032525.py, line 1)

In [4]:
np.__version__  # Version of numpy 

'1.24.3'

##### Creating Arrays from Python Lists

In [5]:
# integer array:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [6]:
"""Remember that unlike Python lists, NumPy is constrained to arrays that all contain
the same type. If types do not match, NumPy will upcast if possible (here, integers are
upcast to floating point)"""
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [12]:
np.array([1, 2, 3, 4], dtype='int')


array([1, 2, 3, 4])

In [9]:
np.array?

In [13]:
# nested lists result in multidimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

##### Creating Arrays from Scratch

In [14]:
#Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
# Create a 3x5 floating-point array filled with 1s
np.ones((3, 5),dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [18]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [19]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [21]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.47457774, 0.21357508, 0.72448158],
       [0.87586226, 0.34287902, 0.40511118],
       [0.5980251 , 0.97622781, 0.04693015]])

In [23]:
#Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[-0.47707214, -1.18296309, -0.82219336],
       [ 0.32500985, -0.92082264, -0.1603628 ],
       [-1.3080733 ,  2.06057616,  0.25302411]])

In [24]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[1, 5, 7],
       [9, 1, 9],
       [1, 1, 1]])

In [25]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that
# memory location
np.empty(4)

array([0.25, 0.5 , 0.75, 1.  ])

### NumPy Standard Data Types
NumPy arrays contain values of a single type, so it is important to have detailed
knowledge of those types and their limitations. Because NumPy is built in C, the
types will be familiar to users of C, Fortran, and other related languages.

###### Data type Description<br>
bool_ Boolean (True or False) stored as a byte<br>
int_ Default integer type (same as C long; normally either int64 or int32)<br>
intc Identical to C int (normally int32 or int64)<br>
intp Integer used for indexing (same as C ssize_t; normally either int32 or int64)<br>
int8 Byte (–128 to 127)<br>
int16 Integer (–32768 to 32767)<br>
int32 Integer (–2147483648 to 2147483647)<br>
int64 Integer (–9223372036854775808 to 9223372036854775807)<br>
uint8 Unsigned integer (0 to 255)<br>
uint16 Unsigned integer (0 to 65535)<br>
uint32 Unsigned integer (0 to 4294967295)<br>
uint64 Unsigned integer (0 to 18446744073709551615)<br>
float_ Shorthand for float64<br>
float16 Half-precision float: sign bit, 5 bits exponent, 10 bits mantissa<br>
float32 Single-precision float: sign bit, 8 bits exponent, 23 bits mantissa<br>
float64 Double-precision float: sign bit, 11 bits exponent, 52 bits mantissa<br>
complex_ Shorthand for complex128<br>
complex64 Complex number, represented by two 32-bit floats<br>
complex128 Complex number, represented by two 64-bit floats<br>
Refer for  more advanced datatypes in https://numpy.org

##### The Basics of NumPy Arrays

Attributes of arrays:
Determining the size, shape, memory consumption, and data types of arrays

In [48]:
np.random.seed(0) # seed for reproducibility
x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array

In [46]:
print(x1)

[5 0 3 3 7 9]


In [49]:
print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [50]:
print(x3)

[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [51]:
"""Each array has attributes ndim (the number of dimensions), shape (the size of each
dimension), and size (the total size of the array):"""
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [52]:
print("dtype:", x3.dtype)

dtype: int64


In [53]:
"""Other attributes include itemsize, which lists the size (in bytes) of each array element,
and nbytes, which lists the total size (in bytes) of the array"""
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


In [54]:
#Array Indexing: Accessing Single Elements
x2[0, 0]

3

In [55]:
x2[2, -1]

7

In [57]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [62]:
#Array Slicing: Accessing Subarrays
#x[start:stop:step]
#One-dimensional subarrays
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
print(x[:5] )# first five elements
print (x[5:]) # elements after index 5
print(x[4:7]) # middle subarray

[0 1 2 3 4]
[5 6 7 8 9]
[4 5 6]


In [63]:
x[::2] # every other element

array([0, 2, 4, 6, 8])

In [64]:
x[1::2] # every other element, starting at index 1

array([1, 3, 5, 7, 9])

In [65]:
"""A potentially confusing case is when the step value is negative. In this case, the
defaults for start and stop are swapped. This becomes a convenient way to reverse
an array"""
x[::-1] # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [66]:
x[5::-2] # reversed every other from index 5

array([5, 3, 1])

##### Multidimensional subarrays
Multidimensional slices work in the same way, with multiple slices separated by commas.
For example:

In [67]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [68]:
x2[:2, :3] # two rows, three columns

array([[12,  5,  2],
       [ 7,  6,  8]])

In [69]:
x2[:3, ::2] # all rows, every other column

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [70]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [77]:
print(x2[:, 0])
print(x2[0, :]) #x2[0]

[12  7  1]
[12  5  2  4]


###### Subarrays as no-copy views

In [87]:
"""One important—and extremely useful—thing to know about array slices is that they
return views rather than copies of the array data. This is one area in which NumPy
array slicing differs from Python list slicing: in lists, slices will be copies"""
print("\nx2\n",x2)
x2_sub = x2[:2, :2]
print("\nx2_sub\n",x2_sub)
x2_sub[0, 0] = 99
print("\nx2_sub\n",x2_sub)
print("\nx2\n",x2)


x2
 [[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]

x2_sub
 [[99  5]
 [ 7  6]]

x2_sub
 [[99  5]
 [ 7  6]]

x2
 [[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [88]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [89]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [90]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


###### Reshaping of Arrays

In [92]:
"""Another useful type of operation is reshaping of arrays. The most flexible way of
doing this is with the reshape() method. For example, if you want to put the numbers
1 through 9 in a 3×3 grid, you can do the following:"""
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [94]:
x = np.array([1, 2, 3])
# row vector via reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [97]:
# row vector via newaxis
x[np.newaxis,:]

array([[1, 2, 3]])

In [98]:
# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [99]:
# column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

###### Array Concatenation and Splitting

In [100]:
x= np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [101]:
z = [99, 99, 99]
np.concatenate([x, y,z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [103]:
# concatenate along the first axis
grid = np.array([[1, 2, 3],[4, 5, 6]])
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [104]:
# concatenate along the second axis
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [105]:
"""For working with arrays of mixed dimensions, it can be clearer to use the np.vstack
(vertical stack) and np.hstack (horizontal stack) functions"""
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],[6, 5, 4]])
# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [106]:
# horizontally stack the arrays
y = np.array([[99],
[99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [123]:
x = np.arange(9)
np.split(x, 3)
"""If `indices_or_sections` is a 1-D array of sorted integers, the entries
    indicate where along `axis` the array is split.  For example,
    ``[2, 3]`` would, for ``axis=0``, result in

      - ary[:2]
      - ary[2:3]
      - ary[3:]"""
np.split(x, [2,3])

[array([0, 1]), array([2]), array([3, 4, 5, 6, 7, 8])]

In [124]:
grid = np.arange(16).reshape((4, 4))
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


###### Universal functions (ufunc)
###### Arithmetic operators implemented in NumPy

+  np.add Addition (e.g., 1 + 1 = 2)<br>
+ np.subtract Subtraction (e.g., 3 - 2 = 1)<br>
+  np.negative Unary negation (e.g., -2)<br>
+  np.multiply Multiplication (e.g., 2 * 3 = 6)<br>
+  np.divide Division (e.g., 3 / 2 = 1.5)
+  np.floor_divide Floor division (e.g., 3 // 2 = 1)<br>
+  np.power Exponentiation (e.g., 2 ** 3 = 8)<br>
+  np.mod Modulus/remainder (e.g., 9 % 4 = 1)<br>

In [126]:
x = np.arange(4)
print("x =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2) # floor division
print("-x = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2 = ", x % 2)

x = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
-x =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2 =  [0 1 0 1]


In [127]:
np.add(x, 2)

array([2, 3, 4, 5])

In [128]:
#Trignometric function 
theta = np.linspace(0, np.pi, 3)
theta

array([0.        , 1.57079633, 3.14159265])

In [130]:
print("theta = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [131]:
#Exponents and logarithms
x = [1, 2, 3]
print("x =", x)
print("e^x =", np.exp(x))
print("2^x =", np.exp2(x))
print("3^x =", np.power(3, x))
x = [1, 2, 4, 10]
print("x =", x)
print("ln(x) =", np.log(x))
print("log2(x) =", np.log2(x))
print("log10(x) =", np.log10(x))

x = [1, 2, 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
2^x = [2. 4. 8.]
3^x = [ 3  9 27]
x = [1, 2, 4, 10]
ln(x) = [0.         0.69314718 1.38629436 2.30258509]
log2(x) = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [132]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

[ 0. 10. 20. 30. 40.]


In [133]:
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


###### Aggregates

In [134]:

"""For binary ufuncs, there are some interesting aggregates that can be computed
directly from the object."""
x = np.arange(1, 7)
np.add.reduce(x)

21

In [135]:
np.multiply.reduce(x)

720

In [136]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15, 21])

In [137]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120, 720])

In [138]:
x = np.arange(1, 6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [141]:
L = np.arange(10)
np.sum(L)

45

In [142]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

40.4 ms ± 1.29 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
188 µs ± 2.38 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [144]:
%timeit min(big_array)
%timeit np.max(big_array)

26.6 ms ± 71.3 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
103 µs ± 3.02 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [145]:
#Multidimensional aggregates
M = np.random.random((3, 4))
print(M)


[[0.0049466  0.25863997 0.62346477 0.90474173]
 [0.71661557 0.699582   0.80401456 0.60471376]
 [0.43905815 0.73525983 0.3703232  0.57361603]]


In [146]:
M.sum()

6.734976167538792

In [147]:
M.min(axis=0)

array([0.0049466 , 0.25863997, 0.3703232 , 0.57361603])

In [148]:
M.max(axis=1)

array([0.90474173, 0.80401456, 0.73525983])

###### Other aggregation functions
Function Name    NaN-safe       Version Description<br>
np.sum          np.nansum        Compute sum of elements<br>
np.prod         np.nanprod       Compute product of elements<br>
np.mean         np.nanmean       Compute median of elements<br>
np.std          np.nanstd        Compute standard deviation<br>
np.var          np.nanvar        Compute variance<br>
np.min          np.nanmin        Find minimum value<br>
np.max          np.nanmax        Find maximum value<br>
np.argmin       np.nanargmin     Find index of minimum value<br>
np.argmax       np.nanargmax     Find index of maximum value<br>
np.median       np.nanmedian     Compute median of elements<br>
np.percentile   np.nanpercentile Compute rank-based statistics of elements<br>
np.any          N/A              Evaluate whether any elements are true<br>
np.all          N/A              Evaluate whether all elements are true<br>

###### Comparison Operators as ufuncs

In [149]:
x = np.array([1, 2, 3, 4, 5])
print(x < 3) # less than
print(x > 3) # greater than
print(x <= 3) # less than or equal
print(x >= 3) # greater than or equal
print(x != 3) # not equal
print(x == 3) # equal

[ True  True False False False]
[False False False  True  True]
[ True  True  True False False]
[False False  True  True  True]
[ True  True False  True  True]
[False False  True False False]


In [152]:
x=np.random.randint(10,size=(3,4))
x

array([[7, 3, 9, 7],
       [6, 9, 6, 7],
       [3, 5, 4, 6]])

In [153]:
# how many values less than 6?
np.count_nonzero(x < 6)

4

In [154]:
np.sum(x < 6)

4

In [155]:
# how many values less than 6 in each row?
np.sum(x < 6, axis=1)

array([1, 0, 3])

In [156]:
# are there any values greater than 8?
np.any(x > 8)

True

In [157]:
# are all values less than 10?
np.all(x < 10)

True